create table cinemas
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    created_by uuid,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    address    text                        not null,
    city       varchar(100)                not null,
    name       varchar(255)                not null
);

alter table cinemas
    owner to neondb_owner;

create table media
(
    id           varchar(255)                not null
        primary key,
    created_at   timestamp(6) with time zone not null,
    created_by   uuid,
    updated_at   timestamp(6) with time zone,
    updated_by   uuid,
    entity_id    integer,
    entity_type  varchar(50),
    file_name    varchar(255)                not null,
    file_type    varchar(50),
    file_url     varchar(500)                not null,
    content_type varchar(255),
    file_key     varchar(255),
    name         varchar(255),
    size         bigint,
    status       boolean,
    url          varchar(255)
);

alter table media
    owner to neondb_owner;

create table promotions
(
    id             integer generated by default as identity
        primary key,
    code           varchar(50)    not null
        constraint ukjdho73ymbyu46p2hh562dk4kk
            unique,
    created_at     timestamp(6)   not null,
    discount_type  varchar(20)    not null
        constraint promotions_discount_type_check
            check ((discount_type)::text = ANY
        ((ARRAY ['PERCENT'::character varying, 'FIXED'::character varying])::text[])),
    discount_value numeric(10, 2) not null,
    end_date       date           not null,
    max_usage      integer        not null,
    start_date     date           not null,
    status         varchar(20)    not null
        constraint promotions_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    used_count     integer        not null
);

alter table promotions
    owner to neondb_owner;

create table rooms
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    created_by  uuid,
    updated_at  timestamp(6) with time zone,
    updated_by  uuid,
    name        varchar(100)                not null,
    total_seats integer                     not null,
    type        varchar(255)                not null
        constraint rooms_type_check
            check ((type)::text = ANY
        ((ARRAY ['STANDARD'::character varying, 'IMAX'::character varying, 'VIP'::character varying, 'FOUR_DX'::character varying])::text[])),
    cinema_id   integer                     not null
        constraint fkjp9bjtvlojbw581bpq23cpw4j
            references cinemas
);

alter table rooms
    owner to neondb_owner;

create table seats
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    created_by  uuid,
    updated_at  timestamp(6) with time zone,
    updated_by  uuid,
    base_price  numeric(10, 2)              not null,
    row_label   varchar(5)                  not null,
    seat_number varchar(10)                 not null,
    type        varchar(255)                not null
        constraint seats_type_check
            check ((type)::text = ANY
        ((ARRAY ['STANDARD'::character varying, 'VIP'::character varying, 'COUPLE'::character varying])::text[])),
    room_id     integer                     not null
        constraint fkg993pi7ucgy616icmddq8u335
            references rooms
);

alter table seats
    owner to neondb_owner;

create table movies
(
    id              integer generated by default as identity
        primary key,
    created_at      timestamp(6) with time zone not null,
    created_by      uuid,
    updated_at      timestamp(6) with time zone,
    updated_by      uuid,
    description     text,
    director        varchar(255)                not null,
    duration        integer                     not null,
    genre           varchar(255)                not null,
    movie_cast      text,
    release_date    date                        not null,
    review_url      varchar(500),
    status          varchar(255)                not null
        constraint movies_status_check
            check ((status)::text = ANY
        ((ARRAY ['COMING_SOON'::character varying, 'NOW_SHOWING'::character varying, 'ENDED'::character varying])::text[])),
    teaser_url      varchar(500),
    title           varchar(500)                not null,
    poster_media_id varchar(255)
        constraint fkkqqcdu24e8664lvdiqdkhjd6s
            references media
);

alter table movies
    owner to neondb_owner;

create table showtimes
(
    id              integer generated by default as identity
        primary key,
    created_at      timestamp(6) with time zone not null,
    created_by      uuid,
    updated_at      timestamp(6) with time zone,
    updated_by      uuid,
    available_seats integer                     not null,
    base_price      numeric(10, 2)              not null,
    end_time        timestamp(6)                not null,
    start_time      timestamp(6)                not null,
    status          varchar(20)                 not null
        constraint showtimes_status_check
            check ((status)::text = ANY
        ((ARRAY ['SCHEDULED'::character varying, 'ONGOING'::character varying, 'ENDED'::character varying, 'CANCELLED'::character varying])::text[])),
    movie_id        integer                     not null
        constraint fkeltpyuei1d5g3n6ikpsjwwil6
            references movies,
    room_id         integer                     not null
        constraint fkrumrrbei9jppryk4teoyoetit
            references rooms
);

alter table showtimes
    owner to neondb_owner;

create table users
(
    id            varchar(255)                not null
        primary key,
    created_at    timestamp(6) with time zone not null,
    created_by    uuid,
    updated_at    timestamp(6) with time zone,
    updated_by    uuid,
    avatar_id     varchar(255),
    email         varchar(100)                not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    full_name     varchar(255)                not null,
    is_lock       boolean                     not null,
    password_hash varchar(255)                not null,
    phone         varchar(20)                 not null
        constraint ukdu5v5sr43g5bfnji4vb8hg5s3
            unique,
    role          varchar(255)                not null
        constraint users_role_check
            check ((role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[]))
    );

alter table users
    owner to neondb_owner;

create table bookings
(
    id              integer generated by default as identity
        primary key,
    created_at      timestamp(6) with time zone not null,
    created_by      uuid,
    updated_at      timestamp(6) with time zone,
    updated_by      uuid,
    discount_amount numeric(10, 2)              not null,
    final_amount    numeric(10, 2)              not null,
    qr_code         varchar(500),
    status          varchar(20)                 not null
        constraint bookings_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])),
    total_amount    numeric(10, 2)              not null,
    promotion_id    integer
        constraint fkk4byobgkjv3y3952wwpxyep7o
            references promotions,
    showtime_id     integer                     not null
        constraint fkc7q4u7vleq90vlvy8c7lmwtyl
            references showtimes,
    user_id         varchar(255)                not null
        constraint fkeyog2oic85xg7hsu2je2lx3s6
            references users
);

alter table bookings
    owner to neondb_owner;

create table booking_details
(
    id            integer generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    created_by    uuid,
    updated_at    timestamp(6) with time zone,
    updated_by    uuid,
    price_at_time numeric(10, 2)              not null,
    seat_number   varchar(10)                 not null,
    booking_id    integer                     not null
        constraint fkkbcan6ybv86uappnh0qtdmvas
            references bookings,
    seat_id       integer                     not null
        constraint fkgphl9xdom8314je7ajy36ov2h
            references seats
);

alter table booking_details
    owner to neondb_owner;

create table notifications
(
    id         integer generated by default as identity
        primary key,
    body       text         not null,
    created_at timestamp(6) not null,
    sent_at    timestamp(6),
    status     varchar(20)  not null
        constraint notifications_status_check
            check ((status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying])::text[])),
    subject    varchar(255) not null,
    type       varchar(20)  not null
        constraint notifications_type_check
            check ((type)::text = ANY
                   ((ARRAY ['EMAIL'::character varying, 'SMS'::character varying, 'PUSH'::character varying])::text[])),
    booking_id integer
        constraint fk87r43mlyr9nnth3xbf0li1ij3
            references bookings,
    user_id    varchar(255) not null
        constraint fk9y21adhxn0ayjhfocscqox7bh
            references users
);

alter table notifications
    owner to neondb_owner;

create table payments
(
    id             integer generated by default as identity
        primary key,
    amount         numeric(10, 2) not null,
    created_at     timestamp(6)   not null,
    method         varchar(30)    not null
        constraint payments_method_check
            check ((method)::text = ANY
        ((ARRAY ['VNPAY'::character varying, 'MOMO'::character varying, 'ZALOPAY'::character varying, 'CASH'::character varying])::text[])),
    paid_at        timestamp(6),
    status         varchar(20)    not null
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])),
    transaction_id varchar(255)
        constraint uklryndveuwa4k5qthti0pkmtlx
            unique,
    booking_id     integer        not null
        constraint fkc52o2b1jkxttngufqp3t7jr3h
            references bookings
);

alter table payments
    owner to neondb_owner;