spring:
  application:
    name: ecom
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    url: jdbc:postgresql://localhost:5432/tmdt_db
    username: postgres
    password: 123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntquang0000@gmail.com
    password: ulwr ckkx kdvi iigc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

store:
  minio:
    host: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    public-bucket: chat-files
    private-bucket: chat-files
    presigned-url-expiration-in-minute: 60
    public-domain: ${MINIO_PUBLIC_DOMAIN:}

server:
  port: 8889
  servlet:
    context-path: /api
  address: 0.0.0.0

jwt:
  secret: bM7nzPj1nksc6mAn9DcO/0gsPpZ2xZVYxvHlTWR8HpqWZ8TgX6O2G5n2U3V7ZQoc1pX0Xg4s6I0vG4b3JSm+QA==